myapp/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('myapp.views',
    url(r'^$', 'register', name='register'),
    url(r'^login$', 'connexion', name='login'),
    url(r'^logout$', 'logout_view', name='logout'),
    url(r'^account$', 'account', name='account'),
    url(r'^personnage/new$', 'addPersonnage'),
    url(r'^changeperso/(?P<id>\d+)$', 'changePerso'),
    url(r'^quete/(?P<id>\d+)$', 'quest'),
    url(r'^fight/(?P<id>\d+)$', 'fight'),
    url(r'^finish_quest/(?P<id>\d+)$', 'finish_quest'),
    url(r'^changeitem/(?P<id>\d+)$', 'changeItem'),
    url(r'^shop$', 'shop'),
)

rpg/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'rpg.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
     url(r'', include('myapp.urls')),
    url(r'^admin/', include(admin.site.urls)),
)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myapp/models.py
from django.db import models
from django.contrib.auth.models import User

def avatar_file_name(instance, filename):
	return '/'.join(['pnj', instance.nom, filename])

def item_file_name(instance, filename):
	return '/'.join(['item', instance.nom, filename])

class Quete(models.Model):
	nom = models.CharField(max_length=50)
	xp = models.IntegerField()
	item = models.ForeignKey('Item')
	
	def __str__(self):
		return self.nom

class Pnj(models.Model):
	nom = models.CharField(max_length=30)
	vie = models.IntegerField()
	force = models.IntegerField()
	xp = models.IntegerField()
	avatar = models.ImageField(upload_to=avatar_file_name)
	enigme = models.CharField(max_length=255)
	quete = models.ForeignKey('Quete')

	def __str__(self):
		return self.nom

class Reponse(models.Model):
	enigme = models.ForeignKey('Pnj')
	answer = models.CharField(max_length=255)

	def __str__(self):
		return self.answer

class Item(models.Model):
	nom = models.CharField(max_length=30)
	panoplie = models.CharField(max_length=30)
	vie = models.IntegerField()
	force = models.IntegerField()
	pourcXp = models.IntegerField()
	choices = (
		('arme', 'arme'),
		('chapeau', 'chapeau'),
		('cape', 'cape'),
		('botte', 'botte'),
	)
	typeOf = models.CharField(max_length=15, choices=choices)
	image = models.ImageField(upload_to=item_file_name)

	def __str__(self):
		return self.nom

class Sac(models.Model):
	personnage = models.ForeignKey('Personnage')
	item = models.ForeignKey('Item')

	def __str__(self):
		return self.personnage.nom + '-> ' + self.item.nom

class Shop(models.Model):
	item = models.ForeignKey('Item')
	inventaire = models.ForeignKey('Sac')

class Personnage(models.Model):
	nom = models.CharField(max_length=30, unique=True)
	xp = models.IntegerField()
	level = models.IntegerField()
	vie = models.IntegerField()
	force = models.IntegerField()
	arme = models.ForeignKey(Sac, related_name='arme', blank=True, null=True)
	chapeau = models.ForeignKey(Sac, related_name='chapeau', blank=True, null=True)
	cape = models.ForeignKey(Sac, related_name='cape', blank=True, null=True)
	botte = models.ForeignKey(Sac, related_name='botte', blank=True, null=True)
	inventaire = models.ManyToManyField(Item, through='sac', blank=True, null=True)
	user = models.ForeignKey(User)


	def __str__(self):
		return self.nom

class Profile(models.Model):
	user = models.OneToOneField(User)
	perso = models.ForeignKey(Personnage)

	def __str__(self):
		return self.perso.nom

class Etape(models.Model):
	personnage = models.ForeignKey(Personnage)
	quete = models.ForeignKey(Quete)
	etape = models.IntegerField()

	def __str__(self):
		return 'etapes: ' + str(self.etape)

myapp/forms.py
from django import forms
from myapp.models import *
from django.contrib.auth.models import User


class UserForm(forms.Form):
	username = forms.CharField(max_length=30)
	email = forms.EmailField(max_length=60)
	password = forms.CharField(max_length=30, min_length=4, widget=forms.PasswordInput)

class LoginForm(forms.Form):
	username = forms.CharField(max_length=60)
	password = forms.CharField(max_length=30, widget=forms.PasswordInput)

class NewPersonnageForm(forms.Form):
	nom = forms.CharField(max_length=30)
	vie = forms.IntegerField(max_value=10, min_value=0)
	force = forms.IntegerField(max_value=10, min_value=0)

class reponseForm(forms.Form):
	reponse = forms.CharField()
	

myapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User
from myapp.forms import *
from django.contrib.auth import authenticate, login, logout
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.forms.util import ErrorList
from django.http import HttpResponse

def not_loggedin_required(function):
    def wrap(request, *args, **kwargs):
        if request.user.is_authenticated():
            return redirect(account)
        else:
            return function(request, *args, **kwargs)
    return wrap

@not_loggedin_required
def register(request):
	if request.method == 'POST':
		form = UserForm(request.POST)
		if form.is_valid():
			username = form.cleaned_data['username']
			email = form.cleaned_data['email']
			password = form.cleaned_data['password']
			user = User.objects.create_user(username, email, password)
			request.session['msg'] = 'inscription réussi'
			return redirect(connexion)
	else:
		form = UserForm()
	return render(request, 'myapp/register.html', locals())


@not_loggedin_required
def connexion(request):
	if request.method =='POST':
		form = LoginForm(request.POST)
		if form.is_valid():
			username = form.cleaned_data['username']
			password = form.cleaned_data['password']
			user = authenticate(username=username, password=password)
			if user is not None:
				if user.is_active:
					login(request, user)
					return redirect(account)
				else:
					msg = 'compte banni'
			else:
				msg = 'invalid password'
	else:
		form = LoginForm()
	return render(request, 'myapp/login.html', locals())

def logout_view(request):
	logout(request)
	return redirect(connexion)


@login_required
def account(request):
	quetes = Quete.objects.all()
	personnages = Personnage.objects.filter(user__username__contains=request.user.username)
	test = getattr(request.user.profile.perso, 'cape')
	try:
		inventory = Sac.objects.filter(personnage=request.user.profile.perso)
	except:
		pass
	return render(request, 'myapp/account.html', locals())

@login_required
def addPersonnage(request):
	if request.method == 'POST':
		f = NewPersonnageForm(request.POST)
		if f.is_valid():
			perso = Personnage()
			perso.nom = f.cleaned_data['nom']
			perso.force = f.cleaned_data['force']
			perso.vie = f.cleaned_data['vie']
			perso.level = 1
			perso.xp = 0
			perso.user = request.user
			if perso.vie + perso.force > 10:
				errors = f._errors.setdefault('__all__', ErrorList())
				errors.append(u"Vous pouvez attribuer seulement 10 points")
			perso.save()
			msg = 'personnage créé'
	else:
		f = NewPersonnageForm()
	return render(request, 'myapp/addPersonnage.html', locals())

@login_required
def changePerso(request, id):
	perso = get_object_or_404(Personnage, id=id)
	if perso.user != request.user:
		return redirect(connexion)
	try:
		request.user.profile.perso = perso
		request.user.profile.save()
	except:
		profile = Profile()
		profile.user = request.user
		profile.perso = perso
		profile.save()
	return redirect(account)

@login_required
def quest(request, id):
	quete, pnjs, etape, pnj = getQueteData(request, id)
	if pnj == False:
		return redirect(finish_quest, id)
	if request.method == 'POST':
		send = True
		f = reponseForm(request.POST)
		if f.is_valid():
			reponse = f.cleaned_data['reponse']
			result = pnj.reponse_set.first().answer
			if reponse != result:
				f.add_error(None, 'mauvaise réponse !')
				return render(request, 'myapp/quete.html', locals())
			updateEtape(request, etape, quete)
			return redirect(quest, id)
	else:
		f = reponseForm()
	return render(request, 'myapp/quete.html', locals())

def getQueteData(request, id):
	quete = get_object_or_404(Quete, id=id)
	pnjs = quete.pnj_set.all()
	etape = Etape.objects.filter(personnage=request.user.profile.perso).filter(quete=quete)

	if not etape:
		pnj = pnjs[0]
	else:
		try:
			pnj = pnjs[etape[0].etape]
		except:	
			pnj = False
	return quete, pnjs, etape, pnj

def combat(perso, pnj):
	persoLife = perso.vie
	pnjLife = pnj.vie
	msg = []
	i = 0
	while i != 1:
		pnjLife -= perso.force
		msg.append(perso.nom + ' enlève ' + str(perso.force) + ' pv !')  
		if pnjLife <= 0:
			pnjLife = 0
		msg.append(pnj.nom + ' a ' + str(pnjLife) + ' pv') 
		if pnjLife <= 0:
			msg.append(pnj.nom + 'est ko') 
			msg.append('Vous avez gagné') 
			result = True
			return msg, result
		persoLife -= pnj.force
		msg.append(pnj.nom + ' enlève ' + str(pnj.force) + ' pv !') 
		if persoLife <= 0:
			persoLife = 0
		msg.append(perso.nom + ' a ' + str(persoLife) + ' pv') 
		if persoLife <= 0:
			msg.append('Vous êtes ko')
			msg.append('Vous avez perdu') 
			result = False
			return msg, result

def updateEtape(request, etape, quete):
	if etape:
		etape[0].etape += 1
		etape[0].save()
	else:
		etape = Etape()
		etape.personnage = request.user.profile.perso
		etape.quete = quete
		etape.etape = 1
		etape.save()
	return

@login_required
def fight(request, id):
	quete, pnjs, etape, pnj = getQueteData(request, id)
	perso = request.user.profile.perso
	msg, result = combat(perso, pnj)
	if result == True:
		updateEtape(request, etape, quete)
		
	return render(request, 'myapp/fight.html', locals())


@login_required
def finish_quest(request, id):
	quete = get_object_or_404(Quete, id=id)
	xp = quete.xp
	item = quete.item
	perso = request.user.profile.perso
	perso.xp += xp
	perso.save()
	bag = Sac()
	bag.personnage = perso
	bag.item = item
	bag.save()
	return render(request, 'myapp/finish_quest.html', locals())


@login_required
def changeItem(request, id):
	item = Sac.objects.get(id=id)
	typeOf = item.item.typeOf
	perso = request.user.profile.perso
	oldItem = getattr(perso, typeOf)
	setattr(perso, typeOf, item)
	if oldItem is not None:
		perso.force -= oldItem.item.force
		perso.vie -= oldItem.item.vie
	perso.vie += item.item.vie
	perso.force += item.item.force
	perso.save()
	return redirect(account)

@login_required
def shop(request):
	if request.method == 'POST':
		itemId = request.POST['item']
		inventaire = get_object_or_404(Sac, id=itemId)
		item = inventaire.item
		article = Shop()
		article.item = item
		article.inventaire = inventaire
		article.save()



	itemsToBuy = Shop.objects.all()
	myItems = Sac.objects.filter(personnage = request.user.profile.perso)


	return render(request, 'myapp/shop.html', locals())

myapp/templates/myapp/account.html
{% extends 'base.html' %}

{% block content %}
<a href="{% url 'myapp.views.addPersonnage' %}">créer un personnage</a>
<a href="{% url 'myapp.views.shop' %}">magasin</a>

{% for quete in quetes %}
	<ul>
		<li><a href="{% url 'myapp.views.quest' quete.id %}">{{quete.nom}}</a></li>
		<li>nombre d'étapes: {{quete.pnj_set.count}}</li>
	</ul>

{% endfor %}


{% for perso in personnages %}
	<ul>
		<li>nom: {{perso.nom}}</li>
		<li>vie: {{perso.vie}}</li>
		<li>force: {{perso.force}}</li>
		<li>level: {{perso.level}}</li>
		<li>xp: {{perso.xp}}</li>
		<li>arme: {{perso.arme}}</li>
		<li>chapeau: {{perso.chapeau}}</li>
		<li>cape: {{perso.cape}}</li>
		<li>botte: {{perso.botte}}</li>
		<li>proprio: {{perso.user.username}}</li>
	</ul>

	{%if perso.profile_set.all %}
		{% for item in inventory %}
			<ul>
				<li>
					{{item.item.nom}}</li>
				<li>{{item.item.typeOf}}</li>
				<li><a href="{% url 'myapp.views.changeItem' item.id %}">{{item.id}}</a></li>
			</ul>
		{% endfor %}
		<p>personnage utilisé</p>
	{% else %}
		<p><a href="{% url 'myapp.views.changePerso' perso.id %}">Utilisé ce personnage</a></p>
	{% endif %}
{% endfor %}


{% endblock %}

myapp/templates/myapp/addPersonnage.html
{% extends 'base.html' %}

{% block content %}
{{msg}}
<form method="POST" action="{% url 'myapp.views.addPersonnage' %}">
	{{f.as_p}}
	{% csrf_token %}
	<input type="submit" value="créer">
</form>
{% endblock %}

myapp/templates/myapp/fight.html
{% extends 'base.html' %}

{% block content %}

{% for m in msg %}
	<p>{{m}}</p>
{% endfor %}

{% if result %}
	<p>Vous avez gagné passé au niveau suivant! <a href="{% url 'myapp.views.quest' id %}">Etape suivante</a></p>

{% else %}
	<p>Vous avez perdu <a href="{% url 'myapp.views.account' %}">retourner à l'accueil</a></p>
{% endif %}

{% endblock %}

myapp/templates/myapp/finish_quest.html
{% extends 'base.html' %}

{% block content %}
vous gagné {{xp}} d'expérience !
{{perso.nom}}
{{perso.xp}}
vous avez gagné l'item {{quete.item.nom}}

{% endblock %}

myapp/templates/myapp/form_reponse.html
{% extends 'quete.html' %}

{% block pnj %}
	<form method="POST" action='{ url "myapp.views.answer" }'>
		<input type="text">
		<input type="submit" value="répondre">
	</form>
{% endblock %}

myapp/templates/myapp/login.html
{% extends 'base.html' %}

{% block content %}
{{msg}}
<form action='{% url "myapp.views.connexion" %}' method="POST">
	{{form.as_p}}
	{% csrf_token %}
	<input type="submit" value="connexion">
</form>

{% endblock %}

myapp/templates/myapp/quete.html
{% extends 'base.html' %}

{% block content %}
{{quete.nom}}
Voulez vous combattre <strong>{{pnj}}</strong> ou répondre à son enigme?
<button id="fight"><a href="{% url 'myapp.views.fight' quete.id %}">combattre</a></button>
<button id="answer">répondre</button>
{% if send %}
	<div>
	{{pnj.enigme}} ?
		<form method="POST" action='{% url "myapp.views.quest" quete.id %}'>
			{% csrf_token %}
			{{f.as_p}}
			<input type="submit" value="répondre" id="submit">
		</form>
	</div>
{% else %}
	<div id="toggle">
	{{pnj.enigme}} ?
		<form method="POST" action='{% url "myapp.views.quest" quete.id %}'>
			{% csrf_token %}
			{{f.as_p}}
			<input type="submit" value="répondre" id="submit">
		</form>
	</div>
{% endif %}

{% endblock %}

myapp/templates/myapp/register.html
{% extends 'base.html' %}

{% block content %}
{{msg}}
{{request.user.username}}
<form method="POST" action='{% url "myapp.views.register" %}'>
	{{form.as_p}}
	{% csrf_token %}
	<input type="submit" value="s'inscrire">
</form> 

{% endblock %}

myapp/templates/myapp/shop.html
{% extends 'base.html' %}

{% block content %}
<a href="{% url 'myapp.views.account' %}">mon compte</a>
<h2>Mettre en vente un article</h2>

<form action="{% url 'myapp.views.shop' %}" method="POST">
	<select name="item">
	  {% for item in myItems %}
	  	<option value="{{item.id}}">{{item.item.nom}}</option>
	  {% endfor %}
 	</select>
	{% csrf_token %}
	<input type="submit" value="mettre en vente">
</form>
<ul>
{% for item in itemsToBuy %}
	<li>{{item.item.nom}}</li>
	<li>force: {{item.item.force}}</li>
	<li>vie: {{item.item.vie}}</li>
	<li>xp supplémentaire: {{item.item.pourcXp}}</li>

{% endfor %}

</ul>
{% endblock %}